/* Australian reference figures found by desk research on 28 Sep 2026.
   Values were taken from search-result text naming each page; confirm on the live page before relying on them. */
window.UW_SOURCES = [
 {
  "id": "gst_rate",
  "item": "GST rate (Australia)",
  "value": 10,
  "unit": "%",
  "gstIncluded": null,
  "effective": "current (unchanged since 2000)",
  "source": "Australian Taxation Office",
  "url": "https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/claiming-gst-credits",
  "note": "Confidence high. Search snippet (ATO): 'If you're registered for GST, you can claim GST credits for the GST included in the price of goods and services you buy for your business'; tax invoice needed for purchases > A$82.50 inc GST; 4-year time limit. ATO pages could not be fetched directly (egress blocked) - verified via search index; retrieved 2026-09-28."
 },
 {
  "id": "gst_input_credits",
  "item": "Input tax credits for GST-registered businesses",
  "value": null,
  "unit": "n/a",
  "gstIncluded": null,
  "effective": "current",
  "source": "Australian Taxation Office",
  "url": "https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/claiming-gst-credits/when-you-can-claim-a-gst-credit",
  "note": "Yes: registered businesses claim GST credits on business purchases via BAS; only business-use portion for mixed use; cannot also deduct the GST in income tax. Search-index level; retrieved 2026-09-28."
 },
 {
  "id": "nmw_hourly_2026",
  "item": "National Minimum Wage (adult, full/part-time)",
  "value": 26.44,
  "unit": "AUD per hour",
  "gstIncluded": null,
  "effective": "from first full pay period on/after 1 July 2026",
  "source": "Fair Work Ombudsman / Fair Work Commission (Annual Wage Review 2026)",
  "url": "https://www.fairwork.gov.au/newsroom/media-releases/2026-media-releases/july-2026/20260701-minimum-wage-increase-media-release",
  "note": "Confidence high (consistent across FWO, FWC and law-firm summaries). Snippet: 'The National Minimum Wage is now $1,004.90 per week ... or $26.44 per hour' (+5.97%). FWC decision announced 2 June 2026: https://www.fwc.gov.au/hearings-decisions/major-cases/annual-wage-reviews/annual-wage-review-2026. Pages seen via search index, not fetched."
 },
 {
  "id": "nmw_weekly_2026",
  "item": "National Minimum Wage weekly (38 hrs)",
  "value": 1004.9,
  "unit": "AUD per week",
  "gstIncluded": null,
  "effective": "1 July 2026",
  "source": "Fair Work Ombudsman",
  "url": "https://www.fairwork.gov.au/about-us/workplace-laws/annual-wage-review/annual-wage-review-2026",
  "note": "Same source as above."
 },
 {
  "id": "nmw_casual_hourly_2026",
  "item": "National Minimum Wage casual rate incl. loading",
  "value": 33.05,
  "unit": "AUD per hour",
  "gstIncluded": null,
  "effective": "1 July 2026",
  "source": "Fair Work Ombudsman",
  "url": "https://www.fairwork.gov.au/newsroom/media-releases/2026-media-releases/july-2026/20260701-minimum-wage-increase-media-release",
  "note": "Snippet: 'Casual employees entitled to the National Minimum Wage must receive at least $33.05 per hour, which includes the 25 per cent casual loading.'"
 },
 {
  "id": "casual_loading",
  "item": "Casual loading",
  "value": 25,
  "unit": "%",
  "gstIncluded": null,
  "effective": "current",
  "source": "Fair Work Ombudsman",
  "url": "https://www.fairwork.gov.au/newsroom/media-releases/2026-media-releases/july-2026/20260701-minimum-wage-increase-media-release",
  "note": "25% casual loading (NMW and most modern awards)."
 },
 {
  "id": "award_increase_2026",
  "item": "Modern award minimum wage increase",
  "value": 4.75,
  "unit": "%",
  "gstIncluded": null,
  "effective": "1 July 2026",
  "source": "Fair Work Ombudsman",
  "url": "https://www.fairwork.gov.au/about-us/workplace-laws/annual-wage-review/annual-wage-review-2026",
  "note": "Award rates +4.75%. Useful to uplift any 2025-26 award rate you already hold."
 },
 {
  "id": "award_aera_ma000080",
  "item": "Amusement, Events and Recreation Award 2020 [MA000080] grade rate",
  "value": null,
  "unit": "AUD per hour",
  "gstIncluded": null,
  "effective": "1 July 2026",
  "source": "Fair Work Ombudsman pay guide",
  "url": "https://portal.fairwork.gov.au/ArticleDocuments/872/amusement-events-and-recreation-award-ma000080-pay-guide.pdf.aspx",
  "note": "NOT FOUND reliably: official pay guide exists at this URL but could not be fetched (egress blocked) and search snippets did not show 2026 grade tables. Third-party aggregator (fairworkmate.com.au) claims Level 1 = $26.44/hr, casual $33.05 - unverified, do not use without checking the pay guide."
 },
 {
  "id": "award_misc_ma000104_l1",
  "item": "Miscellaneous Award 2020 [MA000104] Level 1 (third-party figure)",
  "value": 25.74,
  "unit": "AUD per hour",
  "gstIncluded": null,
  "effective": "1 July 2026",
  "source": "FairWork Mate (aggregator) - official pay guide dated 01/07/2026 exists",
  "url": "https://portal.fairwork.gov.au/ArticleDocuments/872/miscellaneous-award-ma000104-pay-guide.pdf.aspx",
  "note": "LOW confidence: $25.74/hr (casual $32.18) from aggregator snippet; equals FWO's entry-level floor ('at least $978.10 per week or $25.74 per hour'), so may be an entry-level/intro rate only. Verify in official pay guide before use."
 },
 {
  "id": "super_guarantee",
  "item": "Superannuation guarantee rate",
  "value": 12,
  "unit": "% of qualifying earnings",
  "gstIncluded": null,
  "effective": "from 1 July 2025; applies 2026-27",
  "source": "Australian Taxation Office",
  "url": "https://www.ato.gov.au/tax-rates-and-codes/key-superannuation-rates-and-thresholds/super-guarantee",
  "note": "Confidence high. From 1 July 2026 SG is calculated on 'qualifying earnings' and paid each payday (Payday Super). Max contribution base 2026-27: $270,830 (per quarter-equivalent per ATO snippet). Search-index level."
 },
 {
  "id": "meta_quest_3s_128_rrp",
  "item": "Meta Quest 3S 128GB RRP",
  "value": 569,
  "unit": "AUD each inc GST",
  "gstIncluded": true,
  "effective": "as indexed Sept 2026",
  "source": "Meta Store (en-AU)",
  "url": "https://www.meta.com/au/quest/quest-3s/",
  "note": "MEDIUM-LOW confidence: search summary attributes A$569 (128GB) and A$729 (256GB) to Meta AU store; launch price in Sept 2024 was A$499 (press-start.com.au). Page not fetchable - confirm on the day of purchase. AU consumer prices include GST."
 },
 {
  "id": "meta_quest_3s_256_rrp",
  "item": "Meta Quest 3S 256GB RRP",
  "value": 729,
  "unit": "AUD each inc GST",
  "gstIncluded": true,
  "effective": "as indexed Sept 2026",
  "source": "Meta Store (en-AU)",
  "url": "https://www.meta.com/au/quest/quest-3s/",
  "note": "MEDIUM-LOW confidence; see 128GB note. JB Hi-Fi listing: https://www.jbhifi.com.au/products/meta-quest-3s-256gb (price not visible)."
 },
 {
  "id": "meta_quest_3_512_rrp",
  "item": "Meta Quest 3 512GB RRP",
  "value": 799,
  "unit": "AUD each inc GST",
  "gstIncluded": true,
  "effective": "since 30 Sept 2024 price drop (may have changed)",
  "source": "Press Start (Australian games news) / Meta Store AU",
  "url": "https://press-start.com.au/news/2024/09/30/meta-quest-3-price-drop-australia/",
  "note": "MEDIUM-LOW confidence: 'now has a permanent price of $799, which is $250 off the original price' (orig A$1,049). Dated 2024; current Meta AU price not directly verified: https://www.meta.com/au/quest/quest-3/buy-now/"
 },
 {
  "id": "projector_7000lm_hire_day",
  "item": "Panasonic PT-DZ780 WUXGA 7,000 lumen DLP projector hire (lens not included)",
  "value": 660,
  "unit": "AUD per day (from)",
  "gstIncluded": null,
  "effective": "listing current Sept 2026",
  "source": "Gecko.rent (AV Hire, Cheltenham VIC / Warehouse Sound Systems, Collingwood VIC)",
  "url": "https://gecko.rent/en/hire-projectors/cheltenham-vic/panasonic-dz780-wuxga-7000-lumen-dlp-projector-lens-not-included-1",
  "note": "MEDIUM confidence: snippet 'available for hire from $660 per day'. Lamp DLP, not laser; lens extra; GST treatment not stated. No Melbourne supplier found publishing 10,000+ lumen laser hire prices (Event Equipment, Corporate AV, NextGen AV all quote-only)."
 },
 {
  "id": "screen_touch_hire_day",
  "item": "TV / interactive touchscreen hire (43-55in touch, 43-65in 4K TV) incl. delivery, install, stand",
  "value": 320,
  "unit": "AUD per day (from)",
  "gstIncluded": null,
  "effective": "listing current Sept 2026",
  "source": "Extreme VR",
  "url": "https://www.extremevr.com.au/interactive-games-hire/TV-and-Touch-Screen-Hire",
  "note": "MEDIUM confidence: 'Hire prices start from $320 per day' including delivery, pick up, installation and stands; operates in Melbourne. 75-86in and kiosk pricing: not found (quote-only at AAOC, Technology Rental, Video Display)."
 },
 {
  "id": "projector_10k_laser_hire",
  "item": "10,000+ lumen laser projector hire Melbourne",
  "value": null,
  "unit": "AUD per day",
  "gstIncluded": null,
  "effective": null,
  "source": "Event Equipment Australia (example)",
  "url": "https://eventequipment.com.au/hire/hire-4k-12000-lumens-projector/",
  "note": "NOT FOUND: suppliers list 12,000 lm laser units but quote on request."
 },
 {
  "id": "venue_bighouse_warehouse",
  "item": "Bighouse Arts warehouse space, Coburg North - full day (8 hrs)",
  "value": 550,
  "unit": "AUD per day ex GST",
  "gstIncluded": false,
  "effective": "listing current Sept 2026",
  "source": "Tagvenue (Bighouse Arts listing)",
  "url": "https://www.tagvenue.com/au/rooms/melbourne/24687/bighouse-arts/warehouse-space",
  "note": "MEDIUM confidence: '$550 + GST' full day, '$350 + GST' half day; own site (https://www.bighousearts.com.au/warehouse-space) shows $500 + GST full day, overtime $80/hr + GST. Rate is for film/photo shoots - NOT a long-run public exhibition rate."
 },
 {
  "id": "venue_gallery_nicholas_bldg",
  "item": "LifeImages Gallery & Studio7.12, Nicholas Building, Melbourne CBD",
  "value": 500,
  "unit": "AUD per week (min 2 weeks)",
  "gstIncluded": null,
  "effective": "listing current Sept 2026",
  "source": "Creative Spaces (City of Melbourne program)",
  "url": "https://www.creativespaces.net.au/space/life-images-gallery-studio7-12",
  "note": "Small artist-run gallery - scale reference only."
 },
 {
  "id": "venue_fitzroy_exhibition_3wk",
  "item": "Exhibition space, Fitzroy - 3-week hire incl. install/de-install",
  "value": 3900,
  "unit": "AUD per 3 weeks (largest space; smallest $1,900)",
  "gstIncluded": null,
  "effective": "listing current Sept 2026",
  "source": "Creative Spaces",
  "url": "https://www.creativespaces.net.au/space/exhibition-spaces-available",
  "note": "Small gallery scale reference only."
 },
 {
  "id": "venue_meat_market",
  "item": "Meat Market, North Melbourne (City of Melbourne)",
  "value": null,
  "unit": "AUD",
  "gstIncluded": null,
  "effective": null,
  "source": "City of Melbourne",
  "url": "https://www.melbourne.vic.gov.au/meat-market",
  "note": "NOT FOUND: quote-based ('pricing depends on the nature and duration of hire plus a hirer's not-for-profit or funding status'; contact 03 9329 9966). Abbotsford Convent also publishes rates in venue packs (e.g. https://abbotsfordconvent.com.au/venues-for-hire/) but figures not retrieved."
 },
 {
  "id": "pli_single_event_marsh",
  "item": "Single-event public liability insurance, $20m cover (Category A, <1,000 attendees, <=3 days)",
  "value": 275,
  "unit": "AUD per event",
  "gstIncluded": null,
  "effective": "current listing",
  "source": "Marsh Australia",
  "url": "https://www.au.marsh.com/business/events-festivals/small-event-insurance.html",
  "note": "MEDIUM confidence: Category A priced at $275 with $20m public & products liability. One-off event product, NOT an annual policy for a months-long exhibition."
 },
 {
  "id": "pli_cover_level",
  "item": "Typical public liability cover required by councils/venues",
  "value": 20000000,
  "unit": "AUD cover limit",
  "gstIncluded": null,
  "effective": "current",
  "source": "Marsh Australia / Informa Australia",
  "url": "https://www.au.marsh.com/business/events-festivals/small-event-insurance.html",
  "note": "$20m is standard; many Victorian councils/venues require $20m. Annual premium for a long-running exhibition: NOT FOUND from an insurer page with published figures."
 },
 {
  "id": "worksafe_vic_avg_premium",
  "item": "WorkSafe Victoria average premium rate",
  "value": 1.8,
  "unit": "% of rateable remuneration",
  "gstIncluded": null,
  "effective": "2026-27",
  "source": "WorkSafe Victoria (via broker summaries Adroit / HRD)",
  "url": "https://www.worksafe.vic.gov.au/industry-rates-and-key-dates",
  "note": "MEDIUM confidence: average premium 'remain at 1.8 per cent - unchanged for the fourth year in a row'. Actual employer rate depends on WIC industry rate; see https://adroit.com.au/victorian-2026-27-workcover-update/"
 },
 {
  "id": "vdo_small_biz_citipower",
  "item": "Victorian Default Offer small business annual bill, CitiPower zone (Melbourne CBD/inner), 10,000 kWh/yr flat",
  "value": 1481,
  "unit": "AUD per year (at 10,000 kWh)",
  "gstIncluded": null,
  "effective": "1 July 2026 - 30 June 2027",
  "source": "Essential Services Commission (via search index)",
  "url": "https://www.esc.vic.gov.au/electricity-and-gas/prices-tariffs-and-benchmarks/victorian-default-offer/victorian-default-offer-price-review-2026-27",
  "note": "MEDIUM-LOW confidence: snippet lists small business VDO '$1748 in AusNet; $1481 in CitiPower; $1563 in Jemena; $1633 in Powercor and $1529 in United Energy'. Includes supply charges, so $1481/10,000 kWh = ~14.8c/kWh is only a rough all-in average. Exact c/kWh usage rate NOT FOUND (in ESC Final Decision Paper: https://www.esc.vic.gov.au/sites/default/files/documents/Victorian%20Default%20Offer%202026%E2%80%9327%20Final%20Decision%20Paper.pdf). GST treatment not confirmed."
 },
 {
  "id": "print3d_msd_makerspace",
  "item": "3D printing commercial job rate (University of Melbourne MSD Maker Spaces, per aggregator)",
  "value": null,
  "unit": "AUD 85-120 per hour",
  "gstIncluded": null,
  "effective": "2026 guide",
  "source": "Zeal 3D (price guide citing MSD)",
  "url": "https://www.zeal3dprinting.com.au/3d-printing-cost-melbourne/",
  "note": "LOW confidence: secondary source; 'A$85-A$120 per hour'. Not large-format-specific. Filament raw cost A$20-60/kg per same guide. Large-format per-kg rate: NOT FOUND."
 },
 {
  "id": "cnc_foam_rate",
  "item": "CNC foam carving / fabrication rate Melbourne",
  "value": null,
  "unit": "AUD per hour",
  "gstIncluded": null,
  "effective": null,
  "source": "C5 Systems / Branchflowers CNC (quote-only)",
  "url": "https://c5systems.com.au/",
  "note": "NOT FOUND: Melbourne providers do not publish rates."
 },
 {
  "id": "motion_designer_salary",
  "item": "Motion designer average salary Australia (modelled)",
  "value": 115435,
  "unit": "AUD per year (approx $55/hr)",
  "gstIncluded": null,
  "effective": "2026",
  "source": "ERI Economic Research Institute",
  "url": "https://www.erieri.com/salary/job/motion-designer/australia",
  "note": "LOW-MEDIUM confidence: modelled estimate, range $79,073-$141,061. Employee salary, not freelance day rate. Glassdoor motion graphics designer: $63,500 (25th)-$97,750 (75th): https://www.glassdoor.com.au/Salaries/motion-graphics-designer-salary-SRCH_KO0,24.htm"
 },
 {
  "id": "animator_3d_salary",
  "item": "3D animator average salary Australia (modelled)",
  "value": 126768,
  "unit": "AUD per year (approx $61/hr)",
  "gstIncluded": null,
  "effective": "2026",
  "source": "ERI Economic Research Institute",
  "url": "https://www.erieri.com/salary/job/3d-animator/australia",
  "note": "LOW-MEDIUM confidence: range $88,864-$154,023. Freelance AUD day rates from Hays/Robert Walters/MEAA: NOT FOUND."
 },
 {
  "id": "reg_pope_city_of_melbourne",
  "item": "Place of Public Entertainment occupancy permit (POPE-OP) - City of Melbourne",
  "value": null,
  "unit": "link",
  "gstIncluded": null,
  "effective": "current",
  "source": "City of Melbourne",
  "url": "https://www.melbourne.vic.gov.au/public-entertainment-and-temporary-structure-siting-approvals",
  "note": "POPE = area > 500 m2 used for public entertainment; Building Act ss49-50 require occupancy permit; issued by municipal building surveyor."
 },
 {
  "id": "reg_vba_bpc_pope",
  "item": "VBA practice note BP-10 Places of public entertainment (regulator now Building and Plumbing Commission from 1 July 2025)",
  "value": null,
  "unit": "link",
  "gstIncluded": null,
  "effective": "2023 note; BPC since 1 July 2025",
  "source": "Victorian Building Authority / Building and Plumbing Commission",
  "url": "https://www.vba.vic.gov.au/__data/assets/pdf_file/0014/152330/Building_BP_10-Places-of-public-entertainment.pdf",
  "note": "BPC search: https://www.bpc.vic.gov.au/search?query=Places+of+Public+Entertainment"
 },
 {
  "id": "reg_premises_standards",
  "item": "Disability (Access to Premises - Buildings) Standards 2010",
  "value": null,
  "unit": "link",
  "gstIncluded": null,
  "effective": "in force 1 May 2011; amended 23 Nov 2024 to reference AS 1428.1-2021",
  "source": "Federal Register of Legislation / ABCB",
  "url": "https://www.legislation.gov.au/F2010L00668",
  "note": "ABCB note on amendment: https://www.abcb.gov.au/news/2025/amended-premises-standards-and-ncc"
 },
 {
  "id": "reg_as1428_1",
  "item": "AS 1428.1-2021 Design for access and mobility",
  "value": null,
  "unit": "link",
  "gstIncluded": null,
  "effective": "2021 edition referenced by Access Code",
  "source": "Australian Building Codes Board",
  "url": "https://www.abcb.gov.au/news/2025/amended-premises-standards-and-ncc",
  "note": "Standard itself is paywalled (Standards Australia)."
 }
];
