// Well-known songs from the 1960s and 1970s that carers can pick from.
// This is a list of titles and artists only: Hazel does not include any
// recordings (they are under copyright). The carer attaches a copy they own.
export interface CatalogueSong {
  title: string
  artist: string
  year: number
}

export const SONG_CATALOGUE: CatalogueSong[] = [
  { title: 'Stand by Me', artist: 'Ben E. King', year: 1961 },
  { title: 'Can’t Help Falling in Love', artist: 'Elvis Presley', year: 1961 },
  { title: 'Crying', artist: 'Roy Orbison', year: 1961 },
  { title: 'Crazy', artist: 'Patsy Cline', year: 1961 },
  { title: 'Return to Sender', artist: 'Elvis Presley', year: 1962 },
  { title: 'Summer Holiday', artist: 'Cliff Richard and the Shadows', year: 1963 },
  { title: 'She Loves You', artist: 'The Beatles', year: 1963 },
  { title: 'I Want to Hold Your Hand', artist: 'The Beatles', year: 1963 },
  { title: 'Oh, Pretty Woman', artist: 'Roy Orbison', year: 1964 },
  { title: 'Downtown', artist: 'Petula Clark', year: 1964 },
  { title: 'Everybody Loves Somebody', artist: 'Dean Martin', year: 1964 },
  { title: 'I’ll Never Find Another You', artist: 'The Seekers', year: 1964 },
  { title: 'Yesterday', artist: 'The Beatles', year: 1965 },
  { title: 'The Carnival Is Over', artist: 'The Seekers', year: 1965 },
  { title: 'It’s Not Unusual', artist: 'Tom Jones', year: 1965 },
  { title: 'Unchained Melody', artist: 'The Righteous Brothers', year: 1965 },
  { title: 'Georgy Girl', artist: 'The Seekers', year: 1966 },
  { title: 'Good Vibrations', artist: 'The Beach Boys', year: 1966 },
  { title: 'Strangers in the Night', artist: 'Frank Sinatra', year: 1966 },
  { title: 'You Don’t Have to Say You Love Me', artist: 'Dusty Springfield', year: 1966 },
  { title: 'What a Wonderful World', artist: 'Louis Armstrong', year: 1967 },
  { title: 'Release Me', artist: 'Engelbert Humperdinck', year: 1967 },
  { title: 'Daydream Believer', artist: 'The Monkees', year: 1967 },
  { title: 'Hey Jude', artist: 'The Beatles', year: 1968 },
  { title: 'Delilah', artist: 'Tom Jones', year: 1968 },
  { title: 'Congratulations', artist: 'Cliff Richard', year: 1968 },
  { title: 'Mrs. Robinson', artist: 'Simon & Garfunkel', year: 1968 },
  { title: 'Suspicious Minds', artist: 'Elvis Presley', year: 1969 },
  { title: 'In the Ghetto', artist: 'Elvis Presley', year: 1969 },
  { title: 'Here Comes the Sun', artist: 'The Beatles', year: 1969 },
  { title: 'Sweet Caroline', artist: 'Neil Diamond', year: 1969 },
  { title: 'My Way', artist: 'Frank Sinatra', year: 1969 },
  { title: 'A Boy Named Sue', artist: 'Johnny Cash', year: 1969 },
  { title: 'Let It Be', artist: 'The Beatles', year: 1970 },
  { title: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', year: 1970 },
  { title: '(They Long to Be) Close to You', artist: 'The Carpenters', year: 1970 },
  { title: 'Your Song', artist: 'Elton John', year: 1970 },
  { title: 'Take Me Home, Country Roads', artist: 'John Denver', year: 1971 },
  { title: 'Eagle Rock', artist: 'Daddy Cool', year: 1971 },
  { title: 'American Pie', artist: 'Don McLean', year: 1971 },
  { title: 'Top of the World', artist: 'The Carpenters', year: 1972 },
  { title: 'Crocodile Rock', artist: 'Elton John', year: 1972 },
  { title: 'Burning Love', artist: 'Elvis Presley', year: 1972 },
  { title: 'Clair', artist: 'Gilbert O’Sullivan', year: 1972 },
  { title: 'Waterloo', artist: 'ABBA', year: 1974 },
  { title: 'I Honestly Love You', artist: 'Olivia Newton-John', year: 1974 },
  { title: 'Rhinestone Cowboy', artist: 'Glen Campbell', year: 1975 },
  { title: 'Dancing Queen', artist: 'ABBA', year: 1976 },
  { title: 'Fernando', artist: 'ABBA', year: 1976 },
  { title: 'Howzat', artist: 'Sherbet', year: 1976 },
  { title: 'How Deep Is Your Love', artist: 'Bee Gees', year: 1977 },
  { title: 'Dreams', artist: 'Fleetwood Mac', year: 1977 },
  { title: 'Love Is in the Air', artist: 'John Paul Young', year: 1977 },
  { title: 'Reminiscing', artist: 'Little River Band', year: 1978 },
]
