// world.js — everything about the world lives here.
// Edit this file to change the map. You shouldn't need to touch map.js.

// The map uses a simple x/y coordinate grid, not real latitude/longitude.
// Think of it as a sheet 1000 tall and 1778 wide (16:9).
// Coordinates are written [y, x] — y first, counting UP from the bottom.
export const WORLD_HEIGHT = 1000;
export const WORLD_WIDTH = 1778;

// ---------------------------------------------------------------------------
// ZOOM LEVELS
// ---------------------------------------------------------------------------
// Each level is one image covering the whole world. They stack on top of each
// other and cross-fade as you zoom, so going from the valley to the Keymaker's
// bench feels like one continuous move.
//
// Zoom is counted in steps in from the whole valley: 0 is the valley filling
// the frame on whatever screen you are on, 1 is twice as close, 2 is four
// times as close. That way a phone and a projector see the same thing.
//
// `fadeInAt` is the zoom where the image starts appearing.
// `fadeInBy` is the zoom where it's fully visible.
// The first level has no fade — it's the base and is always there.
//
// Each level's artwork is drawn at the size it will be read at: the valley is
// the whole sheet, the village has houses you can count, one house fills the
// frame, and the bench is drawn inside the workshop's own footprint. Every
// place below lands at a zoom where one level is settled, never mid-fade.
//
// The four images in /images are generated by `node tools/make-art.mjs`.
// To use your own artwork instead, drop four images of the same aspect ratio
// into /images and point `file` at them — nothing else needs to change.
export const LEVELS = [
  {
    id: 'valley',
    file: 'images/01-valley.svg',
    label: 'The valley',
    fadeInAt: null,
    fadeInBy: null,
  },
  {
    id: 'village',
    file: 'images/02-village.svg',
    label: 'The village',
    fadeInAt: 0.5,
    fadeInBy: 1.2,
  },
  {
    id: 'house',
    file: 'images/03-house.svg',
    label: 'One house',
    fadeInAt: 1.75,
    fadeInBy: 2.05,
  },
  {
    id: 'bench',
    file: 'images/04-bench.svg',
    label: "The Keymaker's bench",
    fadeInAt: 2.35,
    fadeInBy: 2.8,
  },
];

// ---------------------------------------------------------------------------
// PLACES
// ---------------------------------------------------------------------------
// Every place on the map. `at` is [y, x]. `zoom` is how many steps in from
// the whole valley the camera travels when you search for it or click its pin.
// `search` holds the words that should fly you here.
export const PLACES = [
  {
    id: 'workshop',
    name: "The Keymaker's workshop",
    at: [300, 430],
    zoom: 2.8,
    kind: 'character',
    blurb:
      "She cuts a key for every lantern that comes down the river. One key, one door, one lit window. She has done this her whole life.",
    body: 'This is the pancreas. The keys are insulin.',
    search: ['keymaker', 'workshop', 'insulin', 'pancreas', 'keys'],
  },
  {
    id: 'river',
    name: 'The river',
    at: [500, 900],
    zoom: 1.3,
    kind: 'water',
    blurb:
      'It runs through the whole valley, day and night, carrying whatever arrives from the kitchen upstairs.',
    body: 'This is the bloodstream.',
    search: ['river', 'blood', 'bloodstream', 'water'],
  },
  {
    id: 'lanterns',
    name: 'Lanterns on the water',
    at: [472, 1180],
    zoom: 1.7,
    kind: 'light',
    blurb:
      'They arrive after every meal, warm and welcome. A few is a good evening. A hundred, every hour, is something else.',
    body: 'This is sugar from food.',
    search: ['lantern', 'lanterns', 'sugar', 'sweet', 'food', 'rice', 'bread'],
  },
  {
    id: 'lit-house',
    name: 'A house with its window lit',
    at: [710, 830],
    zoom: 2.1,
    kind: 'house-lit',
    blurb: 'Fed, warm, and getting on with the evening.',
    body: 'This is a cell that has taken in the sugar it needs.',
    search: ['lit', 'house', 'cell', 'fed', 'window'],
  },
  {
    id: 'stuck-door',
    name: 'The door that sticks',
    at: [768, 620],
    zoom: 2.1,
    kind: 'house-stuck',
    blurb:
      'The key used to turn easily here. Now it needs a bigger key, and then a bigger one after that.',
    body: 'This is insulin resistance.',
    search: ['stuck', 'door', 'resistance', 'insulin resistance', 'harder'],
  },
  {
    id: 'dark-house',
    name: 'A house gone dark',
    at: [818, 430],
    zoom: 2.1,
    kind: 'house-dark',
    blurb:
      'Nobody could get a key to turn here tonight. The house is still standing. The window is just out.',
    body: 'This is a cell going unfed.',
    search: ['dark', 'unlit', 'out', 'hungry'],
  },
  {
    id: 'dancing-village',
    name: 'The village that dances',
    at: [720, 1420],
    zoom: 1.75,
    kind: 'dancing',
    blurb:
      'When this village moves, its doors swing open on their own. No keys needed. The Keymaker can sit down.',
    body: 'These are muscles. Moving muscle takes in sugar without insulin.',
    search: ['dance', 'dancing', 'muscle', 'walk', 'walking', 'move', 'moving', 'exercise'],
  },
];

// ---------------------------------------------------------------------------
// THE LANTERN PATH
// ---------------------------------------------------------------------------
// Lanterns drift along these points, from upstream to downstream, on a loop.
// Add or move points to follow the river in your own image.
export const RIVER_PATH = [
  [188, 2020],
  [258, 1820],
  [294, 1620],
  [376, 1440],
  [444, 1300],
  [472, 1180],
  [454, 1040],
  [500, 900],
  [548, 770],
  [514, 640],
  [488, 500],
  [530, 360],
  [564, 200],
  [538, 40],
  [570, -160],
];

// How many lanterns drift at once, and how long one trip takes (seconds).
export const LANTERN_COUNT = 7;
export const LANTERN_TRIP_SECONDS = 42;
