// ============================================================
// server.js — the ONLY file that talks to the Anthropic API.
//
// It does two simple jobs:
//   1. Serves the web pages in the /public folder.
//   2. Answers POST /api/scenes: takes a transcript + language,
//      asks Claude for a summary and scenes, and returns JSON.
//
// Your API key lives in a file called ".env" next to this file
// (see .env.example). It NEVER reaches the browser.
//
// Run it with:   npm start        (then open http://localhost:3000)
// Demo mode:     MOCK=1 npm start (canned answer, no API key needed)
// ============================================================

const http = require("http");
const fs = require("fs");
const path = require("path");
const os = require("os");

// ---- Load the .env file (tiny built-in version, no library needed) ----
// Each line looks like:  ANTHROPIC_API_KEY=sk-ant-xxxx
try {
  const envText = fs.readFileSync(path.join(__dirname, ".env"), "utf8");
  for (const line of envText.split("\n")) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (match && !line.trim().startsWith("#") && !(match[1] in process.env)) {
      // Strip optional surrounding quotes from the value.
      process.env[match[1]] = match[2].trim().replace(/^["']|["']$/g, "");
    }
  }
} catch {
  // No .env file yet — that's OK; we show a friendly error when the API is used.
}

const { Anthropic } = require("@anthropic-ai/sdk");

const PORT = process.env.PORT || 3000;
const MOCK = process.env.MOCK === "1"; // demo mode: no API call, canned answer

// ---- The fixed picture library -------------------------------------
// The AI may ONLY pick from this list. It never draws its own pictures.
// Each ID matches a hand-drawn SVG in public/illustrations.js.
const ILLUSTRATION_IDS = [
  "doctor_patient", // doctor and patient talking
  "taking_tablet",  // taking a tablet / medicine
  "calendar",       // next appointment / a date
  "blood_test",     // blood test / sample
  "drinking_water", // drink water
  "walking",        // exercise / walking
  "healthy_food",   // healthy plate of food
  "heart",          // heart / blood pressure
  "lungs",          // lungs / breathing
  "sleeping",       // sleep / rest
  "warning",        // something to watch out for
  "phone_call",     // call the clinic
  "question",       // something unclear
  "family",         // family / carers
  "thumbs_up",      // good news / doing well
];

// Languages the app supports. "name" is used inside the AI prompt.
const LANGUAGES = {
  en: { name: "English" },
  vi: { name: "Vietnamese" },
  ar: { name: "Arabic" },
  zh: { name: "Simplified Chinese" },
};

// The fixed final scene, shown after every video (never generated by AI).
const DISCLAIMER = {
  en: "This is a summary, not medical advice. Ask your clinic if anything is unclear.",
  vi: "Đây là bản tóm tắt, không phải lời khuyên y tế. Hãy hỏi phòng khám nếu có điều gì chưa rõ.",
  ar: "هذا ملخص وليس نصيحة طبية. اسأل عيادتك إذا كان هناك أي شيء غير واضح.",
  zh: "这是一份摘要，不是医疗建议。如有不清楚的地方，请咨询您的诊所。",
};

// ---- The instructions we give the AI (the "safety rules" live here) ----
function buildSystemPrompt(languageName) {
  return `You turn a transcript of a doctor's appointment into a short, simple
picture-story for the patient and their family.

You will receive the transcript. Reply with:
1. "summary": one paragraph in plain English at a grade-5 reading level.
2. "summary_translated": that same paragraph in ${languageName}.
3. "scenes": 4 to 6 scenes covering the most important points, in a
   sensible order (what happened, what to do next).

Each scene has:
- "caption": at most 12 words, plain English, grade-5 reading level.
- "caption_translated": the caption in ${languageName}, equally simple.
- "excerpt": the exact words from the transcript this scene came from,
  copied verbatim (a short quote, not a paraphrase).
- "illustration": the best matching picture ID from the fixed list.
  You may ONLY use these IDs — never invent new ones.

SAFETY RULES — follow these exactly:
- NEVER state a medicine dose or how often to take it unless those exact
  words appear in the transcript. If the transcript says the dose, you may
  repeat it word for word; otherwise leave it out entirely.
- If anything medical is unclear or you are unsure what was meant, the
  caption for that scene must be exactly "Check this with your doctor."
  (translated as well) with the "question" illustration.
- Never add facts, diagnoses, or advice that are not in the transcript.
- Do NOT add a closing disclaimer scene — the app adds one automatically.

If the target language is English, "summary_translated" and every
"caption_translated" simply repeat the English text.`;
}

// The exact JSON shape we want back. The API enforces this schema,
// including the fixed list of picture IDs, so we never get bad JSON.
function buildOutputSchema() {
  return {
    type: "json_schema",
    schema: {
      type: "object",
      properties: {
        summary: { type: "string" },
        summary_translated: { type: "string" },
        scenes: {
          type: "array",
          items: {
            type: "object",
            properties: {
              caption: { type: "string" },
              caption_translated: { type: "string" },
              excerpt: { type: "string" },
              illustration: { type: "string", enum: ILLUSTRATION_IDS },
            },
            required: ["caption", "caption_translated", "excerpt", "illustration"],
            additionalProperties: false,
          },
        },
      },
      required: ["summary", "summary_translated", "scenes"],
      additionalProperties: false,
    },
  };
}

// ---- Ask Claude to build the scenes --------------------------------
async function generateScenes(transcript, language) {
  const languageName = LANGUAGES[language].name;

  const client = new Anthropic(); // reads ANTHROPIC_API_KEY from the environment

  // "fallbacks" is a safety net: if the main model declines the request,
  // the API automatically retries it on another Claude model in the same call.
  const response = await client.beta.messages.create({
    model: "claude-opus-5",
    max_tokens: 16000,
    betas: ["server-side-fallback-2026-07-01"],
    fallbacks: "default",
    system: buildSystemPrompt(languageName),
    output_config: { format: buildOutputSchema() },
    messages: [
      {
        role: "user",
        content:
          `Target language: ${languageName}\n\n` +
          `Transcript of the appointment:\n"""\n${transcript}\n"""`,
      },
    ],
  });

  if (response.stop_reason === "refusal") {
    throw new FriendlyError(
      "The AI declined to process this transcript. Please try different wording, or check the text is really from a medical appointment."
    );
  }

  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock) {
    throw new FriendlyError("The AI returned an empty answer. Please try again.");
  }
  return JSON.parse(textBlock.text);
}

// Double-check the AI's answer before it reaches the browser,
// then add the fixed disclaimer scene at the end.
function cleanResult(raw, language) {
  const scenes = (Array.isArray(raw.scenes) ? raw.scenes : [])
    .filter((s) => s && s.caption && s.excerpt)
    .slice(0, 6) // never more than 6 AI scenes
    .map((s) => ({
      caption: String(s.caption),
      caption_translated: String(s.caption_translated || s.caption),
      excerpt: String(s.excerpt),
      // Unknown picture ID? Fall back to the question mark.
      illustration: ILLUSTRATION_IDS.includes(s.illustration) ? s.illustration : "question",
    }));

  if (scenes.length === 0) {
    throw new FriendlyError("The AI could not find enough medical content in that text. Please check the transcript.");
  }

  // The fixed final scene — always present, never AI-written.
  scenes.push({
    caption: DISCLAIMER.en,
    caption_translated: DISCLAIMER[language],
    excerpt: "This closing reminder is added by the app itself, not taken from your recording.",
    illustration: "phone_call",
  });

  return {
    language,
    summary: String(raw.summary || ""),
    summary_translated: String(raw.summary_translated || raw.summary || ""),
    scenes,
  };
}

// A canned answer for demo mode (MOCK=1) — lets you try the whole app
// with no API key. Mirrors what the real API returns.
const MOCK_RESULT = {
  summary:
    "The doctor said your blood pressure is a little high. You will start one new tablet, amlodipine 5 mg once a day. You need a blood test next week, and you should walk more and eat less salt. You will come back in four weeks to see how things are going.",
  summary_translated: "",
  scenes: [
    { caption: "Your blood pressure is a little high.", caption_translated: "", excerpt: "your blood pressure is still running a bit high", illustration: "heart" },
    { caption: "Take one new tablet each day: amlodipine 5 mg.", caption_translated: "", excerpt: "start you on amlodipine 5 milligrams, one tablet once a day", illustration: "taking_tablet" },
    { caption: "Get a blood test next week.", caption_translated: "", excerpt: "get a blood test next week before we go any further", illustration: "blood_test" },
    { caption: "Walk 30 minutes most days. Eat less salt.", caption_translated: "", excerpt: "a 30 minute walk most days, and cutting down on salty food", illustration: "walking" },
    { caption: "Come back in 4 weeks.", caption_translated: "", excerpt: "see you again in four weeks to check the pressure", illustration: "calendar" },
  ],
};

// A small error type whose message is safe to show to the user.
class FriendlyError extends Error {}

// ---- Handle POST /api/scenes ---------------------------------------
async function handleScenesRequest(req, res) {
  // Read the request body (a small JSON object).
  let body = "";
  for await (const chunk of req) {
    body += chunk;
    if (body.length > 500_000) { req.destroy(); return; } // sanity cap
  }

  let transcript, language;
  try {
    const parsed = JSON.parse(body);
    transcript = String(parsed.transcript || "").trim();
    language = LANGUAGES[parsed.language] ? parsed.language : "en";
  } catch {
    return sendJson(res, 400, { error: "Bad request." });
  }

  if (transcript.length < 40) {
    return sendJson(res, 400, { error: "That transcript looks too short. Please paste the full conversation." });
  }
  if (transcript.length > 100_000) {
    return sendJson(res, 400, { error: "That transcript is very long. Please trim it to the main part of the appointment." });
  }

  // Demo mode — no API key needed.
  if (MOCK) {
    await new Promise((r) => setTimeout(r, 1200)); // pretend to think
    const mock = JSON.parse(JSON.stringify(MOCK_RESULT));
    mock.summary_translated = mock.summary;
    mock.scenes.forEach((s) => (s.caption_translated = s.caption));
    return sendJson(res, 200, cleanResult(mock, language));
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    return sendJson(res, 503, {
      error: "No API key set up yet. Copy .env.example to .env and add your Anthropic API key (or run with MOCK=1 for a demo).",
    });
  }

  try {
    const raw = await generateScenes(transcript, language);
    return sendJson(res, 200, cleanResult(raw, language));
  } catch (err) {
    console.error("API error:", err);
    if (err instanceof FriendlyError) {
      return sendJson(res, 502, { error: err.message });
    }
    if (err instanceof Anthropic.AuthenticationError) {
      return sendJson(res, 502, { error: "The API key was rejected. Please check the key in your .env file." });
    }
    if (err instanceof Anthropic.RateLimitError) {
      return sendJson(res, 502, { error: "The AI service is busy right now. Please wait a minute and try again." });
    }
    if (err instanceof Anthropic.APIError) {
      return sendJson(res, 502, { error: "The AI service returned an error. Please try again." });
    }
    return sendJson(res, 502, { error: "Could not reach the AI service. Check your internet connection and try again." });
  }
}

function sendJson(res, status, obj) {
  const data = JSON.stringify(obj);
  res.writeHead(status, { "Content-Type": "application/json; charset=utf-8" });
  res.end(data);
}

// ---- Serve the files in /public ------------------------------------
const PUBLIC_DIR = path.join(__dirname, "public");
const CONTENT_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
};

function serveStatic(req, res) {
  // Map "/" to the main page, and block sneaky paths like "../".
  const urlPath = decodeURIComponent(req.url.split("?")[0]);
  const safePath = path.normalize(urlPath).replace(/^(\.\.[/\\])+/, "");
  let filePath = path.join(PUBLIC_DIR, safePath === "/" || safePath === "\\" ? "index.html" : safePath);
  if (!filePath.startsWith(PUBLIC_DIR)) {
    res.writeHead(403); return res.end("Forbidden");
  }
  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404, { "Content-Type": "text/plain" });
      return res.end("Not found");
    }
    res.writeHead(200, { "Content-Type": CONTENT_TYPES[path.extname(filePath)] || "application/octet-stream" });
    res.end(data);
  });
}

// ---- Start the server ----------------------------------------------
const server = http.createServer((req, res) => {
  if (req.method === "POST" && req.url === "/api/scenes") {
    handleScenesRequest(req, res).catch((err) => {
      console.error("Unexpected error:", err);
      sendJson(res, 500, { error: "Something went wrong on the server." });
    });
    return;
  }
  serveStatic(req, res);
});

server.listen(PORT, "0.0.0.0", () => {
  console.log("");
  console.log("  Visit Recap is running!");
  console.log(`  On this computer:  http://localhost:${PORT}`);
  // Also print addresses that work from a phone on the same Wi-Fi.
  for (const list of Object.values(os.networkInterfaces())) {
    for (const net of list || []) {
      if (net.family === "IPv4" && !net.internal) {
        console.log(`  On your phone:     http://${net.address}:${PORT}   (same Wi-Fi)`);
      }
    }
  }
  if (MOCK) console.log("  DEMO MODE is on (MOCK=1): using a canned example, no API key needed.");
  else if (!process.env.ANTHROPIC_API_KEY) {
    console.log("  NOTE: no API key found. Copy .env.example to .env and add your key.");
  }
  console.log("");
});
